targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scalars:
            numeric:
              type: double
            bigint:
              type: int
            uuid:
              type: String
          clients:
            - graphql_flutter